name: 'bitcoin_etl'
version: '1.0.0'
config-version: 2
profile: 'bitcoin_etl'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
analysis-paths: ['analyses']
macro-paths: ['macros']

target-path: 'target'
clean-targets: ['target']
log-path: 'logs'

models:
  bitcoin_etl:
    +materialized: view
